### ISSUE TITLE
Config salt fixation + possible credential leakage in _dev.php

### ISSUE THREAD

**Issue by netcarver** [kreativan/wirekit-core#4]
@kreativan Hi, just stumbled on this repo and wanted to say thank you for creating it. I've taken a quick look around and created a couple of PRs to flag up what might be small issues.

The config file has a fixed salt. I'm not sure if PW regenerates the salt on initial installation or if your code does elsewhere? Also, there might be a little credential leakage in one of the files too - but again, I'm not  sure.

Thanks again.

**Comment by kreativan** [comment]
Hi, thank you for your PRs! Stupidly in a rush, i made a push without cleaning up the files... :/

Salt is handled by processwire, no custom code related. Processwire randomises the string on each install (as far as i know). `$config->tableSalt` is in config.php is included by ProcessExportProfile module. When i compare it with a dev version which "wirekit core" originated from its different.
